export const ORDER_STATUS = [
  'PENDING',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELED',
  'RETURN_REQUESTED',
  'RETURNING',
  'RETURNED',
];

export const ORDER_STATUS_PENDING = 'PENDING';
export const ORDER_STATUS_PROCESSING = 'PROCESSING';
export const ORDER_STATUS_SHIPPED = 'SHIPPED';
export const ORDER_STATUS_DELIVERED = 'DELIVERED';
export const ORDER_STATUS_CANCELED = 'CANCELED';
export const ORDER_STATUS_RETURN_REQUESTED = 'RETURN_REQUESTED';
export const ORDER_STATUS_RETURNING = 'RETURNING';
export const ORDER_STATUS_RETURNED = 'RETURNED';
